// Data Wilayah Indonesia - 38 Provinsi dan Kabupaten/Kota
// Sumber: Data BPS 2024

export interface Province {
  code: string;
  name: string;
  cities: City[];
}

export interface City {
  code: string;
  name: string;
  type: "Kota" | "Kabupaten";
}

export const provinces: Province[] = [
  {
    code: "11",
    name: "Aceh",
    cities: [
      { code: "1101", name: "Kabupaten Aceh Selatan", type: "Kabupaten" },
      { code: "1102", name: "Kabupaten Aceh Tenggara", type: "Kabupaten" },
      { code: "1103", name: "Kabupaten Aceh Timur", type: "Kabupaten" },
      { code: "1104", name: "Kabupaten Aceh Tengah", type: "Kabupaten" },
      { code: "1105", name: "Kabupaten Aceh Barat", type: "Kabupaten" },
      { code: "1106", name: "Kabupaten Aceh Besar", type: "Kabupaten" },
      { code: "1107", name: "Kabupaten Pidie", type: "Kabupaten" },
      { code: "1108", name: "Kabupaten Aceh Utara", type: "Kabupaten" },
      { code: "1109", name: "Kabupaten Simeulue", type: "Kabupaten" },
      { code: "1110", name: "Kabupaten Aceh Singkil", type: "Kabupaten" },
      { code: "1111", name: "Kabupaten Bireuen", type: "Kabupaten" },
      { code: "1112", name: "Kabupaten Aceh Barat Daya", type: "Kabupaten" },
      { code: "1113", name: "Kabupaten Gayo Lues", type: "Kabupaten" },
      { code: "1114", name: "Kabupaten Aceh Tamiang", type: "Kabupaten" },
      { code: "1115", name: "Kabupaten Nagan Raya", type: "Kabupaten" },
      { code: "1116", name: "Kabupaten Aceh Jaya", type: "Kabupaten" },
      { code: "1117", name: "Kabupaten Bener Meriah", type: "Kabupaten" },
      { code: "1118", name: "Kabupaten Pidie Jaya", type: "Kabupaten" },
      { code: "1171", name: "Kota Banda Aceh", type: "Kota" },
      { code: "1172", name: "Kota Sabang", type: "Kota" },
      { code: "1173", name: "Kota Langsa", type: "Kota" },
      { code: "1174", name: "Kota Lhokseumawe", type: "Kota" },
      { code: "1175", name: "Kota Subulussalam", type: "Kota" },
    ],
  },
  {
    code: "12",
    name: "Sumatera Utara",
    cities: [
      { code: "1201", name: "Kabupaten Nias", type: "Kabupaten" },
      { code: "1202", name: "Kabupaten Mandailing Natal", type: "Kabupaten" },
      { code: "1203", name: "Kabupaten Tapanuli Selatan", type: "Kabupaten" },
      { code: "1204", name: "Kabupaten Tapanuli Tengah", type: "Kabupaten" },
      { code: "1205", name: "Kabupaten Tapanuli Utara", type: "Kabupaten" },
      { code: "1206", name: "Kabupaten Toba Samosir", type: "Kabupaten" },
      { code: "1207", name: "Kabupaten Labuhan Batu", type: "Kabupaten" },
      { code: "1208", name: "Kabupaten Asahan", type: "Kabupaten" },
      { code: "1209", name: "Kabupaten Simalungun", type: "Kabupaten" },
      { code: "1210", name: "Kabupaten Dairi", type: "Kabupaten" },
      { code: "1211", name: "Kabupaten Karo", type: "Kabupaten" },
      { code: "1212", name: "Kabupaten Deli Serdang", type: "Kabupaten" },
      { code: "1213", name: "Kabupaten Langkat", type: "Kabupaten" },
      { code: "1214", name: "Kabupaten Nias Selatan", type: "Kabupaten" },
      { code: "1215", name: "Kabupaten Humbang Hasundutan", type: "Kabupaten" },
      { code: "1216", name: "Kabupaten Pakpak Bharat", type: "Kabupaten" },
      { code: "1217", name: "Kabupaten Samosir", type: "Kabupaten" },
      { code: "1218", name: "Kabupaten Serdang Bedagai", type: "Kabupaten" },
      { code: "1219", name: "Kabupaten Batu Bara", type: "Kabupaten" },
      { code: "1220", name: "Kabupaten Padang Lawas Utara", type: "Kabupaten" },
      { code: "1221", name: "Kabupaten Padang Lawas", type: "Kabupaten" },
      { code: "1222", name: "Kabupaten Labuhan Batu Selatan", type: "Kabupaten" },
      { code: "1223", name: "Kabupaten Labuhan Batu Utara", type: "Kabupaten" },
      { code: "1224", name: "Kabupaten Nias Utara", type: "Kabupaten" },
      { code: "1225", name: "Kabupaten Nias Barat", type: "Kabupaten" },
      { code: "1271", name: "Kota Sibolga", type: "Kota" },
      { code: "1272", name: "Kota Tanjung Balai", type: "Kota" },
      { code: "1273", name: "Kota Pematang Siantar", type: "Kota" },
      { code: "1274", name: "Kota Tebing Tinggi", type: "Kota" },
      { code: "1275", name: "Kota Medan", type: "Kota" },
      { code: "1276", name: "Kota Binjai", type: "Kota" },
      { code: "1277", name: "Kota Padangsidimpuan", type: "Kota" },
      { code: "1278", name: "Kota Gunungsitoli", type: "Kota" },
    ],
  },
  {
    code: "13",
    name: "Sumatera Barat",
    cities: [
      { code: "1301", name: "Kabupaten Kepulauan Mentawai", type: "Kabupaten" },
      { code: "1302", name: "Kabupaten Pesisir Selatan", type: "Kabupaten" },
      { code: "1303", name: "Kabupaten Padang", type: "Kabupaten" },
      { code: "1304", name: "Kabupaten Solok", type: "Kabupaten" },
      { code: "1305", name: "Kabupaten Sijunjung", type: "Kabupaten" },
      { code: "1306", name: "Kabupaten Tanah Datar", type: "Kabupaten" },
      { code: "1307", name: "Kabupaten Padang Pariaman", type: "Kabupaten" },
      { code: "1308", name: "Kabupaten Agam", type: "Kabupaten" },
      { code: "1309", name: "Kabupaten Lima Puluh Kota", type: "Kabupaten" },
      { code: "1310", name: "Kabupaten Pasaman", type: "Kabupaten" },
      { code: "1311", name: "Kabupaten Solok Selatan", type: "Kabupaten" },
      { code: "1312", name: "Kabupaten Dharmasraya", type: "Kabupaten" },
      { code: "1313", name: "Kabupaten Pasaman Barat", type: "Kabupaten" },
      { code: "1371", name: "Kota Padang", type: "Kota" },
      { code: "1372", name: "Kota Solok", type: "Kota" },
      { code: "1373", name: "Kota Sawah Lunto", type: "Kota" },
      { code: "1374", name: "Kota Padang Panjang", type: "Kota" },
      { code: "1375", name: "Kota Bukittinggi", type: "Kota" },
      { code: "1376", name: "Kota Payakumbuh", type: "Kota" },
      { code: "1377", name: "Kota Pariaman", type: "Kota" },
    ],
  },
  {
    code: "14",
    name: "Riau",
    cities: [
      { code: "1401", name: "Kabupaten Kuantan Singingi", type: "Kabupaten" },
      { code: "1402", name: "Kabupaten Indragiri Hulu", type: "Kabupaten" },
      { code: "1403", name: "Kabupaten Indragiri Hilir", type: "Kabupaten" },
      { code: "1404", name: "Kabupaten Pelalawan", type: "Kabupaten" },
      { code: "1405", name: "Kabupaten Sijak", type: "Kabupaten" },
      { code: "1406", name: "Kabupaten Kampar", type: "Kabupaten" },
      { code: "1407", name: "Kabupaten Rokan Hulu", type: "Kabupaten" },
      { code: "1408", name: "Kabupaten Bengkalis", type: "Kabupaten" },
      { code: "1409", name: "Kabupaten Rokan Hilir", type: "Kabupaten" },
      { code: "1410", name: "Kabupaten Kepulauan Meranti", type: "Kabupaten" },
      { code: "1471", name: "Kota Pekanbaru", type: "Kota" },
      { code: "1472", name: "Kota Dumai", type: "Kota" },
    ],
  },
  {
    code: "15",
    name: "Jambi",
    cities: [
      { code: "1501", name: "Kabupaten Kerinci", type: "Kabupaten" },
      { code: "1502", name: "Kabupaten Merangin", type: "Kabupaten" },
      { code: "1503", name: "Kabupaten Sarolangun", type: "Kabupaten" },
      { code: "1504", name: "Kabupaten Batang Hari", type: "Kabupaten" },
      { code: "1505", name: "Kabupaten Muaro Jambi", type: "Kabupaten" },
      { code: "1506", name: "Kabupaten Tanjung Jabung Timur", type: "Kabupaten" },
      { code: "1507", name: "Kabupaten Tanjung Jabung Barat", type: "Kabupaten" },
      { code: "1508", name: "Kabupaten Tebo", type: "Kabupaten" },
      { code: "1509", name: "Kabupaten Bungo", type: "Kabupaten" },
      { code: "1571", name: "Kota Jambi", type: "Kota" },
      { code: "1572", name: "Kota Sungai Penuh", type: "Kota" },
    ],
  },
  {
    code: "16",
    name: "Sumatera Selatan",
    cities: [
      { code: "1601", name: "Kabupaten Ogan Komering Ulu", type: "Kabupaten" },
      { code: "1602", name: "Kabupaten Ogan Komering Ilir", type: "Kabupaten" },
      { code: "1603", name: "Kabupaten Muara Enim", type: "Kabupaten" },
      { code: "1604", name: "Kabupaten Lahat", type: "Kabupaten" },
      { code: "1605", name: "Kabupaten Musi Rawas", type: "Kabupaten" },
      { code: "1606", name: "Kabupaten Musi Banyuasin", type: "Kabupaten" },
      { code: "1607", name: "Kabupaten Banyuasin", type: "Kabupaten" },
      { code: "1608", name: "Kabupaten Ogan Komering Ulu Selatan", type: "Kabupaten" },
      { code: "1609", name: "Kabupaten Ogan Komering Ulu Timur", type: "Kabupaten" },
      { code: "1610", name: "Kabupaten Ogan Ilir", type: "Kabupaten" },
      { code: "1611", name: "Kabupaten Empat Lawang", type: "Kabupaten" },
      { code: "1612", name: "Kabupaten Penukal Abab Lematang Ilir", type: "Kabupaten" },
      { code: "1613", name: "Kabupaten Musi Rawas Utara", type: "Kabupaten" },
      { code: "1671", name: "Kota Palembang", type: "Kota" },
      { code: "1672", name: "Kota Prabumulih", type: "Kota" },
      { code: "1673", name: "Kota Pagar Alam", type: "Kota" },
      { code: "1674", name: "Kota Lubuklinggau", type: "Kota" },
    ],
  },
  {
    code: "17",
    name: "Bengkulu",
    cities: [
      { code: "1701", name: "Kabupaten Bengkulu Selatan", type: "Kabupaten" },
      { code: "1702", name: "Kabupaten Rejang Lebong", type: "Kabupaten" },
      { code: "1703", name: "Kabupaten Bengkulu Utara", type: "Kabupaten" },
      { code: "1704", name: "Kabupaten Kaur", type: "Kabupaten" },
      { code: "1705", name: "Kabupaten Seluma", type: "Kabupaten" },
      { code: "1706", name: "Kabupaten Mukomuko", type: "Kabupaten" },
      { code: "1707", name: "Kabupaten Lebong", type: "Kabupaten" },
      { code: "1708", name: "Kabupaten Kepahiang", type: "Kabupaten" },
      { code: "1709", name: "Kabupaten Bengkulu Tengah", type: "Kabupaten" },
      { code: "1771", name: "Kota Bengkulu", type: "Kota" },
    ],
  },
  {
    code: "18",
    name: "Lampung",
    cities: [
      { code: "1801", name: "Kabupaten Lampung Barat", type: "Kabupaten" },
      { code: "1802", name: "Kabupaten Tanggamus", type: "Kabupaten" },
      { code: "1803", name: "Kabupaten Lampung Selatan", type: "Kabupaten" },
      { code: "1804", name: "Kabupaten Lampung Timur", type: "Kabupaten" },
      { code: "1805", name: "Kabupaten Lampung Tengah", type: "Kabupaten" },
      { code: "1806", name: "Kabupaten Lampung Utara", type: "Kabupaten" },
      { code: "1807", name: "Kabupaten Way Kanan", type: "Kabupaten" },
      { code: "1808", name: "Kabupaten Tulang Bawang", type: "Kabupaten" },
      { code: "1809", name: "Kabupaten Pesawaran", type: "Kabupaten" },
      { code: "1810", name: "Kabupaten Pringsewu", type: "Kabupaten" },
      { code: "1811", name: "Kabupaten Mesuji", type: "Kabupaten" },
      { code: "1812", name: "Kabupaten Tulang Bawang Barat", type: "Kabupaten" },
      { code: "1813", name: "Kabupaten Pesisir Barat", type: "Kabupaten" },
      { code: "1871", name: "Kota Bandar Lampung", type: "Kota" },
      { code: "1872", name: "Kota Metro", type: "Kota" },
    ],
  },
  {
    code: "19",
    name: "Kepulauan Bangka Belitung",
    cities: [
      { code: "1901", name: "Kabupaten Bangka", type: "Kabupaten" },
      { code: "1902", name: "Kabupaten Belitung", type: "Kabupaten" },
      { code: "1903", name: "Kabupaten Bangka Barat", type: "Kabupaten" },
      { code: "1904", name: "Kabupaten Bangka Tengah", type: "Kabupaten" },
      { code: "1905", name: "Kabupaten Bangka Selatan", type: "Kabupaten" },
      { code: "1906", name: "Kabupaten Belitung Timur", type: "Kabupaten" },
      { code: "1971", name: "Kota Pangkal Pinang", type: "Kota" },
    ],
  },
  {
    code: "21",
    name: "Kepulauan Riau",
    cities: [
      { code: "2101", name: "Kabupaten Karimun", type: "Kabupaten" },
      { code: "2102", name: "Kabupaten Bintan", type: "Kabupaten" },
      { code: "2103", name: "Kabupaten Natuna", type: "Kabupaten" },
      { code: "2104", name: "Kabupaten Lingga", type: "Kabupaten" },
      { code: "2105", name: "Kabupaten Kepulauan Anambas", type: "Kabupaten" },
      { code: "2171", name: "Kota Batam", type: "Kota" },
      { code: "2172", name: "Kota Tanjung Pinang", type: "Kota" },
    ],
  },
  {
    code: "31",
    name: "DKI Jakarta",
    cities: [
      { code: "3101", name: "Kabupaten Kepulauan Seribu", type: "Kabupaten" },
      { code: "3171", name: "Kota Jakarta Selatan", type: "Kota" },
      { code: "3172", name: "Kota Jakarta Timur", type: "Kota" },
      { code: "3173", name: "Kota Jakarta Pusat", type: "Kota" },
      { code: "3174", name: "Kota Jakarta Barat", type: "Kota" },
      { code: "3175", name: "Kota Jakarta Utara", type: "Kota" },
    ],
  },
  {
    code: "32",
    name: "Jawa Barat",
    cities: [
      { code: "3201", name: "Kabupaten Bogor", type: "Kabupaten" },
      { code: "3202", name: "Kabupaten Sukabumi", type: "Kabupaten" },
      { code: "3203", name: "Kabupaten Cianjur", type: "Kabupaten" },
      { code: "3204", name: "Kabupaten Bandung", type: "Kabupaten" },
      { code: "3205", name: "Kabupaten Garut", type: "Kabupaten" },
      { code: "3206", name: "Kabupaten Tasikmalaya", type: "Kabupaten" },
      { code: "3207", name: "Kabupaten Ciamis", type: "Kabupaten" },
      { code: "3208", name: "Kabupaten Kuningan", type: "Kabupaten" },
      { code: "3209", name: "Kabupaten Cirebon", type: "Kabupaten" },
      { code: "3210", name: "Kabupaten Majalengka", type: "Kabupaten" },
      { code: "3211", name: "Kabupaten Sumedang", type: "Kabupaten" },
      { code: "3212", name: "Kabupaten Indramayu", type: "Kabupaten" },
      { code: "3213", name: "Kabupaten Subang", type: "Kabupaten" },
      { code: "3214", name: "Kabupaten Purwakarta", type: "Kabupaten" },
      { code: "3215", name: "Kabupaten Karawang", type: "Kabupaten" },
      { code: "3216", name: "Kabupaten Bekasi", type: "Kabupaten" },
      { code: "3217", name: "Kabupaten Bandung Barat", type: "Kabupaten" },
      { code: "3218", name: "Kabupaten Pangandaran", type: "Kabupaten" },
      { code: "3271", name: "Kota Bogor", type: "Kota" },
      { code: "3272", name: "Kota Sukabumi", type: "Kota" },
      { code: "3273", name: "Kota Bandung", type: "Kota" },
      { code: "3274", name: "Kota Cirebon", type: "Kota" },
      { code: "3275", name: "Kota Bekasi", type: "Kota" },
      { code: "3276", name: "Kota Depok", type: "Kota" },
      { code: "3277", name: "Kota Cimahi", type: "Kota" },
      { code: "3278", name: "Kota Tasikmalaya", type: "Kota" },
      { code: "3279", name: "Kota Banjar", type: "Kota" },
    ],
  },
  {
    code: "33",
    name: "Jawa Tengah",
    cities: [
      { code: "3301", name: "Kabupaten Cilacap", type: "Kabupaten" },
      { code: "3302", name: "Kabupaten Banyumas", type: "Kabupaten" },
      { code: "3303", name: "Kabupaten Purbalingga", type: "Kabupaten" },
      { code: "3304", name: "Kabupaten Banjarnegara", type: "Kabupaten" },
      { code: "3305", name: "Kabupaten Kebumen", type: "Kabupaten" },
      { code: "3306", name: "Kabupaten Purworejo", type: "Kabupaten" },
      { code: "3307", name: "Kabupaten Wonosobo", type: "Kabupaten" },
      { code: "3308", name: "Kabupaten Magelang", type: "Kabupaten" },
      { code: "3309", name: "Kabupaten Boyolali", type: "Kabupaten" },
      { code: "3310", name: "Kabupaten Klaten", type: "Kabupaten" },
      { code: "3311", name: "Kabupaten Sukoharjo", type: "Kabupaten" },
      { code: "3312", name: "Kabupaten Wonogiri", type: "Kabupaten" },
      { code: "3313", name: "Kabupaten Karanganyar", type: "Kabupaten" },
      { code: "3314", name: "Kabupaten Sragen", type: "Kabupaten" },
      { code: "3315", name: "Kabupaten Grobogan", type: "Kabupaten" },
      { code: "3316", name: "Kabupaten Blora", type: "Kabupaten" },
      { code: "3317", name: "Kabupaten Rembang", type: "Kabupaten" },
      { code: "3318", name: "Kabupaten Pati", type: "Kabupaten" },
      { code: "3319", name: "Kabupaten Kudus", type: "Kabupaten" },
      { code: "3320", name: "Kabupaten Jepara", type: "Kabupaten" },
      { code: "3321", name: "Kabupaten Demak", type: "Kabupaten" },
      { code: "3322", name: "Kabupaten Semarang", type: "Kabupaten" },
      { code: "3323", name: "Kabupaten Temanggung", type: "Kabupaten" },
      { code: "3324", name: "Kabupaten Kendal", type: "Kabupaten" },
      { code: "3325", name: "Kabupaten Batang", type: "Kabupaten" },
      { code: "3326", name: "Kabupaten Pekalongan", type: "Kabupaten" },
      { code: "3327", name: "Kabupaten Pemalang", type: "Kabupaten" },
      { code: "3328", name: "Kabupaten Tegal", type: "Kabupaten" },
      { code: "3329", name: "Kabupaten Brebes", type: "Kabupaten" },
      { code: "3371", name: "Kota Magelang", type: "Kota" },
      { code: "3372", name: "Kota Surakarta", type: "Kota" },
      { code: "3373", name: "Kota Salatiga", type: "Kota" },
      { code: "3374", name: "Kota Semarang", type: "Kota" },
      { code: "3375", name: "Kota Pekalongan", type: "Kota" },
      { code: "3376", name: "Kota Tegal", type: "Kota" },
    ],
  },
  {
    code: "34",
    name: "DI Yogyakarta",
    cities: [
      { code: "3401", name: "Kabupaten Kulon Progo", type: "Kabupaten" },
      { code: "3402", name: "Kabupaten Bantul", type: "Kabupaten" },
      { code: "3403", name: "Kabupaten Gunung Kidul", type: "Kabupaten" },
      { code: "3404", name: "Kabupaten Sleman", type: "Kabupaten" },
      { code: "3471", name: "Kota Yogyakarta", type: "Kota" },
    ],
  },
  {
    code: "35",
    name: "Jawa Timur",
    cities: [
      { code: "3501", name: "Kabupaten Pacitan", type: "Kabupaten" },
      { code: "3502", name: "Kabupaten Ponorogo", type: "Kabupaten" },
      { code: "3503", name: "Kabupaten Trenggalek", type: "Kabupaten" },
      { code: "3504", name: "Kabupaten Tulungagung", type: "Kabupaten" },
      { code: "3505", name: "Kabupaten Blitar", type: "Kabupaten" },
      { code: "3506", name: "Kabupaten Kediri", type: "Kabupaten" },
      { code: "3507", name: "Kabupaten Malang", type: "Kabupaten" },
      { code: "3508", name: "Kabupaten Lumajang", type: "Kabupaten" },
      { code: "3509", name: "Kabupaten Jember", type: "Kabupaten" },
      { code: "3510", name: "Kabupaten Banyuwangi", type: "Kabupaten" },
      { code: "3511", name: "Kabupaten Bondowoso", type: "Kabupaten" },
      { code: "3512", name: "Kabupaten Situbondo", type: "Kabupaten" },
      { code: "3513", name: "Kabupaten Probolinggo", type: "Kabupaten" },
      { code: "3514", name: "Kabupaten Pasuruan", type: "Kabupaten" },
      { code: "3515", name: "Kabupaten Sidoarjo", type: "Kabupaten" },
      { code: "3516", name: "Kabupaten Mojokerto", type: "Kabupaten" },
      { code: "3517", name: "Kabupaten Jombang", type: "Kabupaten" },
      { code: "3518", name: "Kabupaten Nganjuk", type: "Kabupaten" },
      { code: "3519", name: "Kabupaten Madiun", type: "Kabupaten" },
      { code: "3520", name: "Kabupaten Magetan", type: "Kabupaten" },
      { code: "3521", name: "Kabupaten Ngawi", type: "Kabupaten" },
      { code: "3522", name: "Kabupaten Bojonegoro", type: "Kabupaten" },
      { code: "3523", name: "Kabupaten Tuban", type: "Kabupaten" },
      { code: "3524", name: "Kabupaten Lamongan", type: "Kabupaten" },
      { code: "3525", name: "Kabupaten Gresik", type: "Kabupaten" },
      { code: "3526", name: "Kabupaten Bangkalan", type: "Kabupaten" },
      { code: "3527", name: "Kabupaten Sampang", type: "Kabupaten" },
      { code: "3528", name: "Kabupaten Pamekasan", type: "Kabupaten" },
      { code: "3529", name: "Kabupaten Sumenep", type: "Kabupaten" },
      { code: "3571", name: "Kota Kediri", type: "Kota" },
      { code: "3572", name: "Kota Blitar", type: "Kota" },
      { code: "3573", name: "Kota Malang", type: "Kota" },
      { code: "3574", name: "Kota Probolinggo", type: "Kota" },
      { code: "3575", name: "Kota Pasuruan", type: "Kota" },
      { code: "3576", name: "Kota Mojokerto", type: "Kota" },
      { code: "3577", name: "Kota Madiun", type: "Kota" },
      { code: "3578", name: "Kota Surabaya", type: "Kota" },
      { code: "3579", name: "Kota Batu", type: "Kota" },
    ],
  },
  {
    code: "36",
    name: "Banten",
    cities: [
      { code: "3601", name: "Kabupaten Pandeglang", type: "Kabupaten" },
      { code: "3602", name: "Kabupaten Lebak", type: "Kabupaten" },
      { code: "3603", name: "Kabupaten Tangerang", type: "Kabupaten" },
      { code: "3604", name: "Kabupaten Serang", type: "Kabupaten" },
      { code: "3671", name: "Kota Tangerang", type: "Kota" },
      { code: "3672", name: "Kota Cilegon", type: "Kota" },
      { code: "3673", name: "Kota Serang", type: "Kota" },
      { code: "3674", name: "Kota Tangerang Selatan", type: "Kota" },
    ],
  },
  {
    code: "51",
    name: "Bali",
    cities: [
      { code: "5101", name: "Kabupaten Jembrana", type: "Kabupaten" },
      { code: "5102", name: "Kabupaten Tabanan", type: "Kabupaten" },
      { code: "5103", name: "Kabupaten Badung", type: "Kabupaten" },
      { code: "5104", name: "Kabupaten Gianyar", type: "Kabupaten" },
      { code: "5105", name: "Kabupaten Klungkung", type: "Kabupaten" },
      { code: "5106", name: "Kabupaten Bangli", type: "Kabupaten" },
      { code: "5107", name: "Kabupaten Karangasem", type: "Kabupaten" },
      { code: "5108", name: "Kabupaten Buleleng", type: "Kabupaten" },
      { code: "5171", name: "Kota Denpasar", type: "Kota" },
    ],
  },
  {
    code: "52",
    name: "Nusa Tenggara Barat",
    cities: [
      { code: "5201", name: "Kabupaten Lombok Barat", type: "Kabupaten" },
      { code: "5202", name: "Kabupaten Lombok Tengah", type: "Kabupaten" },
      { code: "5203", name: "Kabupaten Lombok Timur", type: "Kabupaten" },
      { code: "5204", name: "Kabupaten Sumbawa", type: "Kabupaten" },
      { code: "5205", name: "Kabupaten Dompu", type: "Kabupaten" },
      { code: "5206", name: "Kabupaten Bima", type: "Kabupaten" },
      { code: "5207", name: "Kabupaten Sumbawa Barat", type: "Kabupaten" },
      { code: "5208", name: "Kabupaten Lombok Utara", type: "Kabupaten" },
      { code: "5271", name: "Kota Mataram", type: "Kota" },
      { code: "5272", name: "Kota Bima", type: "Kota" },
    ],
  },
  {
    code: "53",
    name: "Nusa Tenggara Timur",
    cities: [
      { code: "5301", name: "Kabupaten Sumba Barat", type: "Kabupaten" },
      { code: "5302", name: "Kabupaten Sumba Timur", type: "Kabupaten" },
      { code: "5303", name: "Kabupaten Kupang", type: "Kabupaten" },
      { code: "5304", name: "Kabupaten Timor Tengah Selatan", type: "Kabupaten" },
      { code: "5305", name: "Kabupaten Timor Tengah Utara", type: "Kabupaten" },
      { code: "5306", name: "Kabupaten Belu", type: "Kabupaten" },
      { code: "5307", name: "Kabupaten Alor", type: "Kabupaten" },
      { code: "5308", name: "Kabupaten Lembata", type: "Kabupaten" },
      { code: "5309", name: "Kabupaten Flores Timur", type: "Kabupaten" },
      { code: "5310", name: "Kabupaten Sikka", type: "Kabupaten" },
      { code: "5311", name: "Kabupaten Ende", type: "Kabupaten" },
      { code: "5312", name: "Kabupaten Ngada", type: "Kabupaten" },
      { code: "5313", name: "Kabupaten Manggarai", type: "Kabupaten" },
      { code: "5314", name: "Kabupaten Rote Ndao", type: "Kabupaten" },
      { code: "5315", name: "Kabupaten Manggarai Barat", type: "Kabupaten" },
      { code: "5316", name: "Kabupaten Sumba Tengah", type: "Kabupaten" },
      { code: "5317", name: "Kabupaten Sumba Barat Daya", type: "Kabupaten" },
      { code: "5318", name: "Kabupaten Nagekeo", type: "Kabupaten" },
      { code: "5319", name: "Kabupaten Manggarai Timur", type: "Kabupaten" },
      { code: "5320", name: "Kabupaten Sabu Raijua", type: "Kabupaten" },
      { code: "5321", name: "Kabupaten Malaka", type: "Kabupaten" },
      { code: "5371", name: "Kota Kupang", type: "Kota" },
    ],
  },
  {
    code: "61",
    name: "Kalimantan Barat",
    cities: [
      { code: "6101", name: "Kabupaten Sambas", type: "Kabupaten" },
      { code: "6102", name: "Kabupaten Bengkayang", type: "Kabupaten" },
      { code: "6103", name: "Kabupaten Landak", type: "Kabupaten" },
      { code: "6104", name: "Kabupaten Pontianak", type: "Kabupaten" },
      { code: "6105", name: "Kabupaten Sanggau", type: "Kabupaten" },
      { code: "6106", name: "Kabupaten Ketapang", type: "Kabupaten" },
      { code: "6107", name: "Kabupaten Sintang", type: "Kabupaten" },
      { code: "6108", name: "Kabupaten Kapuas Hulu", type: "Kabupaten" },
      { code: "6109", name: "Kabupaten Sekadau", type: "Kabupaten" },
      { code: "6110", name: "Kabupaten Melawi", type: "Kabupaten" },
      { code: "6111", name: "Kabupaten Kayong Utara", type: "Kabupaten" },
      { code: "6112", name: "Kabupaten Kubu Raya", type: "Kabupaten" },
      { code: "6171", name: "Kota Pontianak", type: "Kota" },
      { code: "6172", name: "Kota Singkawang", type: "Kota" },
    ],
  },
  {
    code: "62",
    name: "Kalimantan Tengah",
    cities: [
      { code: "6201", name: "Kabupaten Kotawaringin Barat", type: "Kabupaten" },
      { code: "6202", name: "Kabupaten Kotawaringin Timur", type: "Kabupaten" },
      { code: "6203", name: "Kabupaten Kapuas", type: "Kabupaten" },
      { code: "6204", name: "Kabupaten Barito Selatan", type: "Kabupaten" },
      { code: "6205", name: "Kabupaten Barito Utara", type: "Kabupaten" },
      { code: "6206", name: "Kabupaten Sukamara", type: "Kabupaten" },
      { code: "6207", name: "Kabupaten Lamandau", type: "Kabupaten" },
      { code: "6208", name: "Kabupaten Seruyan", type: "Kabupaten" },
      { code: "6209", name: "Kabupaten Katingan", type: "Kabupaten" },
      { code: "6210", name: "Kabupaten Pulang Pisau", type: "Kabupaten" },
      { code: "6211", name: "Kabupaten Gunung Mas", type: "Kabupaten" },
      { code: "6212", name: "Kabupaten Barito Timur", type: "Kabupaten" },
      { code: "6213", name: "Kabupaten Murung Raya", type: "Kabupaten" },
      { code: "6271", name: "Kota Palangka Raya", type: "Kota" },
    ],
  },
  {
    code: "63",
    name: "Kalimantan Selatan",
    cities: [
      { code: "6301", name: "Kabupaten Tanah Laut", type: "Kabupaten" },
      { code: "6302", name: "Kabupaten Kota Baru", type: "Kabupaten" },
      { code: "6303", name: "Kabupaten Banjar", type: "Kabupaten" },
      { code: "6304", name: "Kabupaten Barito Kuala", type: "Kabupaten" },
      { code: "6305", name: "Kabupaten Tapin", type: "Kabupaten" },
      { code: "6306", name: "Kabupaten Hulu Sungai Selatan", type: "Kabupaten" },
      { code: "6307", name: "Kabupaten Hulu Sungai Tengah", type: "Kabupaten" },
      { code: "6308", name: "Kabupaten Hulu Sungai Utara", type: "Kabupaten" },
      { code: "6309", name: "Kabupaten Tabalong", type: "Kabupaten" },
      { code: "6310", name: "Kabupaten Tanah Bumbu", type: "Kabupaten" },
      { code: "6311", name: "Kabupaten Balangan", type: "Kabupaten" },
      { code: "6371", name: "Kota Banjarmasin", type: "Kota" },
      { code: "6372", name: "Kota Banjarbaru", type: "Kota" },
    ],
  },
  {
    code: "64",
    name: "Kalimantan Timur",
    cities: [
      { code: "6401", name: "Kabupaten Paser", type: "Kabupaten" },
      { code: "6402", name: "Kabupaten Kutai Barat", type: "Kabupaten" },
      { code: "6403", name: "Kabupaten Kutai Kartanegara", type: "Kabupaten" },
      { code: "6404", name: "Kabupaten Kutai Timur", type: "Kabupaten" },
      { code: "6405", name: "Kabupaten Berau", type: "Kabupaten" },
      { code: "6409", name: "Kabupaten Penajam Paser Utara", type: "Kabupaten" },
      { code: "6411", name: "Kabupaten Mahakam Ulu", type: "Kabupaten" },
      { code: "6471", name: "Kota Balikpapan", type: "Kota" },
      { code: "6472", name: "Kota Samarinda", type: "Kota" },
      { code: "6474", name: "Kota Bontang", type: "Kota" },
    ],
  },
  {
    code: "65",
    name: "Kalimantan Utara",
    cities: [
      { code: "6501", name: "Kabupaten Malinau", type: "Kabupaten" },
      { code: "6502", name: "Kabupaten Bulungan", type: "Kabupaten" },
      { code: "6503", name: "Kabupaten Tana Tidung", type: "Kabupaten" },
      { code: "6504", name: "Kabupaten Nunukan", type: "Kabupaten" },
      { code: "6571", name: "Kota Tarakan", type: "Kota" },
    ],
  },
  {
    code: "71",
    name: "Sulawesi Utara",
    cities: [
      { code: "7101", name: "Kabupaten Bolaang Mongondow", type: "Kabupaten" },
      { code: "7102", name: "Kabupaten Minahasa", type: "Kabupaten" },
      { code: "7103", name: "Kabupaten Kepulauan Sangihe", type: "Kabupaten" },
      { code: "7104", name: "Kabupaten Kepulauan Talaud", type: "Kabupaten" },
      { code: "7105", name: "Kabupaten Minahasa Selatan", type: "Kabupaten" },
      { code: "7106", name: "Kabupaten Minahasa Utara", type: "Kabupaten" },
      { code: "7107", name: "Kabupaten Bolaang Mongondow Utara", type: "Kabupaten" },
      { code: "7108", name: "Kabupaten Siau Tagulandang Biaro", type: "Kabupaten" },
      { code: "7109", name: "Kabupaten Minahasa Tenggara", type: "Kabupaten" },
      { code: "7110", name: "Kabupaten Bolaang Mongondow Selatan", type: "Kabupaten" },
      { code: "7111", name: "Kabupaten Bolaang Mongondow Timur", type: "Kabupaten" },
      { code: "7171", name: "Kota Manado", type: "Kota" },
      { code: "7172", name: "Kota Bitung", type: "Kota" },
      { code: "7173", name: "Kota Tomohon", type: "Kota" },
      { code: "7174", name: "Kota Kotamobagu", type: "Kota" },
    ],
  },
  {
    code: "72",
    name: "Sulawesi Tengah",
    cities: [
      { code: "7201", name: "Kabupaten Banggai Kepulauan", type: "Kabupaten" },
      { code: "7202", name: "Kabupaten Banggai", type: "Kabupaten" },
      { code: "7203", name: "Kabupaten Morowali", type: "Kabupaten" },
      { code: "7204", name: "Kabupaten Poso", type: "Kabupaten" },
      { code: "7205", name: "Kabupaten Donggala", type: "Kabupaten" },
      { code: "7206", name: "Kabupaten Toli-Toli", type: "Kabupaten" },
      { code: "7207", name: "Kabupaten Buol", type: "Kabupaten" },
      { code: "7208", name: "Kabupaten Parigi Moutong", type: "Kabupaten" },
      { code: "7209", name: "Kabupaten Tojo Una-Una", type: "Kabupaten" },
      { code: "7210", name: "Kabupaten Sigi", type: "Kabupaten" },
      { code: "7211", name: "Kabupaten Banggai Laut", type: "Kabupaten" },
      { code: "7212", name: "Kabupaten Morowali Utara", type: "Kabupaten" },
      { code: "7271", name: "Kota Palu", type: "Kota" },
    ],
  },
  {
    code: "73",
    name: "Sulawesi Selatan",
    cities: [
      { code: "7301", name: "Kabupaten Kepulauan Selayar", type: "Kabupaten" },
      { code: "7302", name: "Kabupaten Bulukumba", type: "Kabupaten" },
      { code: "7303", name: "Kabupaten Bantaeng", type: "Kabupaten" },
      { code: "7304", name: "Kabupaten Jeneponto", type: "Kabupaten" },
      { code: "7305", name: "Kabupaten Takalar", type: "Kabupaten" },
      { code: "7306", name: "Kabupaten Gowa", type: "Kabupaten" },
      { code: "7307", name: "Kabupaten Sinjai", type: "Kabupaten" },
      { code: "7308", name: "Kabupaten Maros", type: "Kabupaten" },
      { code: "7309", name: "Kabupaten Pangkajene dan Kepulauan", type: "Kabupaten" },
      { code: "7310", name: "Kabupaten Barru", type: "Kabupaten" },
      { code: "7311", name: "Kabupaten Bone", type: "Kabupaten" },
      { code: "7312", name: "Kabupaten Soppeng", type: "Kabupaten" },
      { code: "7313", name: "Kabupaten Wajo", type: "Kabupaten" },
      { code: "7314", name: "Kabupaten Sidenreng Rappang", type: "Kabupaten" },
      { code: "7315", name: "Kabupaten Pinrang", type: "Kabupaten" },
      { code: "7316", name: "Kabupaten Enrekang", type: "Kabupaten" },
      { code: "7317", name: "Kabupaten Luwu", type: "Kabupaten" },
      { code: "7318", name: "Kabupaten Tana Toraja", type: "Kabupaten" },
      { code: "7322", name: "Kabupaten Luwu Utara", type: "Kabupaten" },
      { code: "7325", name: "Kabupaten Luwu Timur", type: "Kabupaten" },
      { code: "7326", name: "Kabupaten Toraja Utara", type: "Kabupaten" },
      { code: "7371", name: "Kota Makassar", type: "Kota" },
      { code: "7372", name: "Kota Parepare", type: "Kota" },
      { code: "7373", name: "Kota Palopo", type: "Kota" },
    ],
  },
  {
    code: "74",
    name: "Sulawesi Tenggara",
    cities: [
      { code: "7401", name: "Kabupaten Buton", type: "Kabupaten" },
      { code: "7402", name: "Kabupaten Muna", type: "Kabupaten" },
      { code: "7403", name: "Kabupaten Konawe", type: "Kabupaten" },
      { code: "7404", name: "Kabupaten Kolaka", type: "Kabupaten" },
      { code: "7405", name: "Kabupaten Konawe Selatan", type: "Kabupaten" },
      { code: "7406", name: "Kabupaten Bombana", type: "Kabupaten" },
      { code: "7407", name: "Kabupaten Wakatobi", type: "Kabupaten" },
      { code: "7408", name: "Kabupaten Kolaka Utara", type: "Kabupaten" },
      { code: "7409", name: "Kabupaten Buton Utara", type: "Kabupaten" },
      { code: "7410", name: "Kabupaten Konawe Utara", type: "Kabupaten" },
      { code: "7411", name: "Kabupaten Kolaka Timur", type: "Kabupaten" },
      { code: "7412", name: "Kabupaten Konawe Kepulauan", type: "Kabupaten" },
      { code: "7413", name: "Kabupaten Muna Barat", type: "Kabupaten" },
      { code: "7414", name: "Kabupaten Buton Tengah", type: "Kabupaten" },
      { code: "7415", name: "Kabupaten Buton Selatan", type: "Kabupaten" },
      { code: "7471", name: "Kota Kendari", type: "Kota" },
      { code: "7472", name: "Kota Baubau", type: "Kota" },
    ],
  },
  {
    code: "75",
    name: "Gorontalo",
    cities: [
      { code: "7501", name: "Kabupaten Boalemo", type: "Kabupaten" },
      { code: "7502", name: "Kabupaten Gorontalo", type: "Kabupaten" },
      { code: "7503", name: "Kabupaten Pohuwato", type: "Kabupaten" },
      { code: "7504", name: "Kabupaten Bone Bolango", type: "Kabupaten" },
      { code: "7505", name: "Kabupaten Gorontalo Utara", type: "Kabupaten" },
      { code: "7571", name: "Kota Gorontalo", type: "Kota" },
    ],
  },
  {
    code: "76",
    name: "Sulawesi Barat",
    cities: [
      { code: "7601", name: "Kabupaten Majene", type: "Kabupaten" },
      { code: "7602", name: "Kabupaten Polewali Mandar", type: "Kabupaten" },
      { code: "7603", name: "Kabupaten Mamasa", type: "Kabupaten" },
      { code: "7604", name: "Kabupaten Mamuju", type: "Kabupaten" },
      { code: "7605", name: "Kabupaten Mamuju Utara", type: "Kabupaten" },
      { code: "7606", name: "Kabupaten Mamuju Tengah", type: "Kabupaten" },
    ],
  },
  {
    code: "81",
    name: "Maluku",
    cities: [
      { code: "8101", name: "Kabupaten Maluku Tenggara Barat", type: "Kabupaten" },
      { code: "8102", name: "Kabupaten Maluku Tenggara", type: "Kabupaten" },
      { code: "8103", name: "Kabupaten Maluku Tengah", type: "Kabupaten" },
      { code: "8104", name: "Kabupaten Buru", type: "Kabupaten" },
      { code: "8105", name: "Kabupaten Kepulauan Aru", type: "Kabupaten" },
      { code: "8106", name: "Kabupaten Seram Bagian Barat", type: "Kabupaten" },
      { code: "8107", name: "Kabupaten Seram Bagian Timur", type: "Kabupaten" },
      { code: "8108", name: "Kabupaten Maluku Barat Daya", type: "Kabupaten" },
      { code: "8109", name: "Kabupaten Buru Selatan", type: "Kabupaten" },
      { code: "8171", name: "Kota Ambon", type: "Kota" },
      { code: "8172", name: "Kota Tual", type: "Kota" },
    ],
  },
  {
    code: "82",
    name: "Maluku Utara",
    cities: [
      { code: "8201", name: "Kabupaten Halmahera Barat", type: "Kabupaten" },
      { code: "8202", name: "Kabupaten Halmahera Tengah", type: "Kabupaten" },
      { code: "8203", name: "Kabupaten Kepulauan Sula", type: "Kabupaten" },
      { code: "8204", name: "Kabupaten Halmahera Selatan", type: "Kabupaten" },
      { code: "8205", name: "Kabupaten Halmahera Utara", type: "Kabupaten" },
      { code: "8206", name: "Kabupaten Halmahera Timur", type: "Kabupaten" },
      { code: "8207", name: "Kabupaten Pulau Morotai", type: "Kabupaten" },
      { code: "8208", name: "Kabupaten Pulau Taliabu", type: "Kabupaten" },
      { code: "8271", name: "Kota Ternate", type: "Kota" },
      { code: "8272", name: "Kota Tidore Kepulauan", type: "Kota" },
    ],
  },
  {
    code: "91",
    name: "Papua Barat",
    cities: [
      { code: "9101", name: "Kabupaten Fakfak", type: "Kabupaten" },
      { code: "9102", name: "Kabupaten Kaimana", type: "Kabupaten" },
      { code: "9103", name: "Kabupaten Teluk Wondama", type: "Kabupaten" },
      { code: "9104", name: "Kabupaten Teluk Bintuni", type: "Kabupaten" },
      { code: "9105", name: "Kabupaten Manokwari", type: "Kabupaten" },
      { code: "9106", name: "Kabupaten Sorong Selatan", type: "Kabupaten" },
      { code: "9107", name: "Kabupaten Sorong", type: "Kabupaten" },
      { code: "9108", name: "Kabupaten Raja Ampat", type: "Kabupaten" },
      { code: "9109", name: "Kabupaten Tambrauw", type: "Kabupaten" },
      { code: "9110", name: "Kabupaten Maybrat", type: "Kabupaten" },
      { code: "9111", name: "Kabupaten Manokwari Selatan", type: "Kabupaten" },
      { code: "9112", name: "Kabupaten Pegunungan Arfak", type: "Kabupaten" },
      { code: "9171", name: "Kota Sorong", type: "Kota" },
    ],
  },
  {
    code: "94",
    name: "Papua",
    cities: [
      { code: "9401", name: "Kabupaten Merauke", type: "Kabupaten" },
      { code: "9402", name: "Kabupaten Jayawijaya", type: "Kabupaten" },
      { code: "9403", name: "Kabupaten Jayapura", type: "Kabupaten" },
      { code: "9404", name: "Kabupaten Nabire", type: "Kabupaten" },
      { code: "9408", name: "Kabupaten Kepulauan Yapen", type: "Kabupaten" },
      { code: "9409", name: "Kabupaten Biak Numfor", type: "Kabupaten" },
      { code: "9410", name: "Kabupaten Paniai", type: "Kabupaten" },
      { code: "9411", name: "Kabupaten Puncak Jaya", type: "Kabupaten" },
      { code: "9412", name: "Kabupaten Mimika", type: "Kabupaten" },
      { code: "9413", name: "Kabupaten Boven Digoel", type: "Kabupaten" },
      { code: "9414", name: "Kabupaten Mappi", type: "Kabupaten" },
      { code: "9415", name: "Kabupaten Asmat", type: "Kabupaten" },
      { code: "9416", name: "Kabupaten Yahukimo", type: "Kabupaten" },
      { code: "9417", name: "Kabupaten Pegunungan Bintang", type: "Kabupaten" },
      { code: "9418", name: "Kabupaten Tolikara", type: "Kabupaten" },
      { code: "9419", name: "Kabupaten Sarmi", type: "Kabupaten" },
      { code: "9420", name: "Kabupaten Keerom", type: "Kabupaten" },
      { code: "9426", name: "Kabupaten Waropen", type: "Kabupaten" },
      { code: "9427", name: "Kabupaten Supiori", type: "Kabupaten" },
      { code: "9428", name: "Kabupaten Mamberamo Raya", type: "Kabupaten" },
      { code: "9429", name: "Kabupaten Nduga", type: "Kabupaten" },
      { code: "9430", name: "Kabupaten Lanny Jaya", type: "Kabupaten" },
      { code: "9431", name: "Kabupaten Mamberamo Tengah", type: "Kabupaten" },
      { code: "9432", name: "Kabupaten Yalimo", type: "Kabupaten" },
      { code: "9433", name: "Kabupaten Puncak", type: "Kabupaten" },
      { code: "9434", name: "Kabupaten Dogiyai", type: "Kabupaten" },
      { code: "9435", name: "Kabupaten Intan Jaya", type: "Kabupaten" },
      { code: "9436", name: "Kabupaten Deiyai", type: "Kabupaten" },
      { code: "9471", name: "Kota Jayapura", type: "Kota" },
    ],
  },
];

export function getProvinces(): Province[] {
  return provinces;
}

export function getCitiesByProvince(provinceCode: string): City[] {
  const province = provinces.find(p => p.code === provinceCode);
  return province?.cities || [];
}

export function getProvinceName(code: string): string {
  return provinces.find(p => p.code === code)?.name || "";
}

export function getCityName(provinceCode: string, cityCode: string): string {
  const province = provinces.find(p => p.code === provinceCode);
  return province?.cities.find(c => c.code === cityCode)?.name || "";
}
